In [43]:
'''
Properties:
grid: a two dimensional array of 1s and 0s (representing white and black cells respectively)
column: horizontal position of ant,
row: ant's vertical position,
direction: ant's current direction (), should default to 0
'''

class Board():
    def __init__(self, grid, column, row, direction):
        self.grid = grid
        self.column = column
        self.row = row
        self.direction = direction
    
    def make_one_turn(self):
        self.move_ant()
        self.set_new_direction()
        self.change_color()
              
    def move_ant(self):
        if self.direction == 'W':
            self.column = self.column - 1
        elif self.direction == 'E':
            self.column = self.column + 1
        elif self.direction == 'S':
            self.row = self.row - 1
        elif self.direction == 'N':
            self.row = self.row + 1
        else:
            print('wrong direction (choose from "W","E","S","N")')
            
    def set_new_direction(self):
        directions_clockwise = {'W':'N', 'N':'E', 'E':'S', 'S':'W'}
        directions_counterclockwise = {'W':'S', 'N':'W', 'E':'N', 'S':'E'}
        if self.grid[self.row][self.column]:
            self.direction = directions_clockwise[self.direction]
        else:
            self.direction = directions_counterclockwise[self.direction]
        
    def change_color(self):
        self.grid[self.row][self.column] = int(not(self.grid[self.row][self.column]))

In [51]:
import numpy as np

iterations = 5
one_grid = [[1,1],[1,1]]
game = Board(one_grid,0,0,'E')
print(np.array(game.grid))

for n in range(iterations):
    game.make_one_turn()
    print(f'Go to: {game.row}, {game.column}.')
    print(np.array(game.grid))
    print(f'Continue in direction {game.direction}')
    print('*******************')

[[1 1]
 [1 1]]
Go to: 0, 1.
[[1 0]
 [1 1]]
Continue in direction S
*******************
Go to: -1, 1.
[[1 0]
 [1 0]]
Continue in direction W
*******************
Go to: -1, 0.
[[1 0]
 [0 0]]
Continue in direction N
*******************
Go to: 0, 0.
[[0 0]
 [0 0]]
Continue in direction E
*******************
Go to: 0, 1.
[[0 1]
 [0 0]]
Continue in direction N
*******************
